### ISSUE TITLE
JAVA 8 with mysql-5.7 throws SQLException

### ISSUE THREAD

**Issue by theodesp** [nikos-glikis/proxymity#1]
The Application throws a lot of exceptions in the form:

java.sql.SQLException: Incorrect usage of UNION and LIMIT
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2505)
    at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1370)
    at com.object0r.tools.proxymity.ProxyCheckerManager.getProxiesToTest(ProxyCheckerManager.java:187)
    at com.object0r.tools.proxymity.ProxyCheckerManager.run(ProxyCheckerManager.java:34)
Fri Sep 23 11:28:58 EEST 2016: Fetched 0 dead proxies for check.

**Comment by nikos-glikis** [comment]
Fixed on [https://github.com/nikos-glikis/proxymity/commit/f59210315c2a9aad11a461e51656fb870164269c](f59210315c2a9aad11a461e51656fb870164269c) can you please verify ?
